stages:
  - build_ui
  - deploy

build:Gulp_Pipeline:
  stage: build_ui
  image: kkarczmarczyk/node-yarn:latest
  script:
    - yarn install
    - ./node_modules/.bin/gulp dist
  artifacts:
    paths:
      - public/
  only:
    - production
    - master

deploy:staging:
  stage: deploy
  image: garland/aws-cli-docker:latest
  variables:
    GIT_STRATEGY: none
  script:
    - aws s3 cp public s3://staging.supagifts.com.au --recursive
  environment:
    name: staging
    url: http://staging.supagifts.com.au
  only:
    - master

deploy:pre-prod:
  stage: deploy
  image: garland/aws-cli-docker:latest
  variables:
    GIT_STRATEGY: none
  script:
    - aws s3 cp public s3://pre-prod.supagifts.com.au --recursive
  environment:
    name: pre-prod
    url: http://pre-prod.supagifts.com.au
  only:
    - production

deploy:production:
  stage: deploy
  image: garland/aws-cli-docker:latest
  variables:
    GIT_STRATEGY: none
  script:
    - rm public/robots.txt
    - aws s3 rm s3://prod-rollback.supagifts.com.au --recursive
    - aws s3 cp s3://supagifts.com.au s3://prod-rollback.supagifts.com.au --recursive
    - aws s3 cp public s3://supagifts.com.au --recursive
  environment:
    name: production
    url: http://www.supagifts.com.au
  when: manual
  only:
    - production
